project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "EDAV-CANCER-PROJECT"
  author:
    - Ben Sullivan (jbs2278)
    - Christine Sharabun (cs4494)
  repo-url: https://bens1858.github.io/EDAV-CANCER-PROJECT/
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


