# Conclusion


  Based on our analysis of the data, the Western world tends to have both higher cancer incidence and cancer mortality rates All countries except European countries tend to have the same gap between incidence and mortality rate despite the existence or lack of operational policy for cancer. Countries that have higher incidence rates have a larger gap between incidence and mortality rates. The larger gap could be attributed to the countries that have higher incidence rates have technologies that are more sensitive to detecting cancer and treating cancer; however, this hypothesis would need to be explored further. As for cumulative risk of incidence of cancer and mortality by age 74, countries with operational policies tend to see higher rates. The highest rates belong to Asia, Europe and North America. It is worth reiterating that the cancer incidence and mortality rates may be estimated differently for each country and that countries may employ different types of policies in response to cancer diagnosis and treatment. This limitation should be explored in future analysis to find more specific trends and identify any bias in the current analysis. 
  
  One of the most significant takeaways is how correlated cancer incidence rates, cancer mortality rates, number of physicians per 1,000 people, and percentage of GDP and domestic spending that goes towards healthcare are. Each of these variables is positively correlated with one another, some more strongly than others. Countries that spend less and have fewer physicians have lower cancer rates and lower mortality rates. Future analysis could explore the nature of this correlation. Perhaps it has to do with methods of reporting - countries that invest less in their healthcare system and have fewer doctors to diagnose end up not finding as much cancer. A true explanation goes beyond the scope of this analysis. Another key trend we uncovered is that Europe tends to be on the high end of most of these metrics while Africa tends to be on the low end of these metrics. The other continents tend to vary more. We see this trend clearly and can customize the variables using our interactive graph.
  
  In terms of cancer estimates in the US, the levels of percentages tend to remain constant over the years 2019-2023. There appear to be no differences in cancer estimates based on Urbanicity, Sex, Region and Poverty level. There appear to be higher rates of cancer in older age groups and among White and American Indian, Alaska Native Americans. One limitation of this dataset is that we cannot track an individual across groups. It would be useful to analyze individuals across groups if that data set was available.
  
  Overall, we conclude that there are differences among cancer and mortality rates across the world based on the amount of government spending on healthcare, the number of physicians per country, and the location of the country. We are somewhat limited with the conclusions we can draw because of some inconsistent methods of reporting and calculations that organizations used to acquire this data, and with needing to average across different years in order to get enough data in enough countries to draw meaningful comparisons. Though these are limitations, we are confident that our estimation techniques are effective enough to still bring insight into this area and to produce interesting and real findings. In the US, there are clear differences of cancer rates in some groups. As for future directions, it would be worthwhile to dive deeper into specific health policies and how those impact cancer incidence and mortality rates across the world and within demographic groups in the US.