# Interactive graph

## Play around with different variables to see how many countries in each continent fit the parameters. Notice any trends?
There are 5 sliders beneath the graph, corresponding to variables we have looked at in the last section. Use the sliders to adjust filters on the data to see which continents have the most countries that fit the parameters you apply. You can adjust any combination of cancer incidence rate, cancer mortality rate, number of physicians in the country, percent of GDP spent on healthcare, and percent of total domestic spending spent on healthcare. The scales set a lower bound for which countries will remain in the graph, and you can see the percentage of the countries in each continent that fit the parameters (height of the bars) and the total number of countries (bar labels).

<style>
  * {
    font-family: sans-serif;
  }
  
  /* Style for the slider container */
  #slider-container {
    background-color: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
    margin-top: 20px;
  }

  /* Style for individual sliders */
  #slider-container input[type="range"] {
    background-color: white;
    border: 1px solid #ccc;
    border-radius: 10px;
  }

  /* Style for the slider labels */
  #slider-container p {
    font-size: 14px;
    font-weight: bold;
    margin-top: 10px;
    color: #333;
  }
</style> 

<div id="plot">
</div>

<div id="slider-container">
  <!-- First slider (Cancer Incidence per 100k) -->
  <input id="slider1" type="range" min="0" max="840" step="1" value="0" style="width: 100%;">
  <p id="sliderLabel1">Cancer Incidence per 100k >= 0</p>

  <!-- Second slider (Cancer Mortality per 100k) -->
  <input id="slider2" type="range" min="0" max="342" step="1" value="0" style="width: 100%;">
  <p id="sliderLabel2">Cancer Mortality per 100k >= 0</p>

  <!-- Third slider (Physicians per 1k) -->
  <input id="slider3" type="range" min="0" max="8.2" step="0.01" value="0" style="width: 100%;">
  <p id="sliderLabel3">Physicians per 1k >= 0</p>

  <!-- Fourth slider (% GDP on Healthcare) -->
  <input id="slider4" type="range" min="0" max="18.6" step="0.1" value="0" style="width: 100%;">
  <p id="sliderLabel4">% GDP on Healthcare >= 0</p>

  <!-- Fifth slider (% Domestic Spending on Healthcare) -->
  <input id="slider5" type="range" min="0" max="27" step="0.1" value="0" style="width: 100%;">
  <p id="sliderLabel5">% Domestic Spending on Healthcare >= 0</p>
</div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>
