# Data

## Description
This is from the United Nations website. The data look at how much countries spend on healthcare as a percentage of GDP and total government expenditure in the years 2005, 2010, 2015, 2018, 2019, and 2020. The data are collected by the World Health Organization (WHO) and reviewed annually using government expenditure records and official statistics. The WHO makes modifications and estimates when needed to ensure consistency and comprehensiveness. Some potential issues with this data involve differences in reporting standards for different countries. Some countries use a calendar year for their reports while others use fiscal years that start on many different days throughout the year depending on the country. The data are posted by the United Nations and was most recently updated on October 25, 2023 using data that was pulled in April 2023. The data are in csv format and have 2,262 rows and 7 columns. It will be imported into R as a csv file. [Link to data.](http://data.un.org/_Docs/SYB/PDFs/SYB66_325_202310_Expenditure%20on%20health.pdf)

This is also from the United Nations website. This data captures the raw number of physicians, nurses, dentists, and pharmacists operating in each country between the years 2000 and 2021. It also records the number of people working in these occupations per 1000 people in each country. The data is collected by the WHO from a combination of national reporting, national censuses, labor force surveys, and administrative and national sources. The definition of a health worker occupation is classified according to the definition of the International Standard Classification of Occupations. The dataset is not without complications. Given the disparate reporting methods of countries around the world, different countries report data for different years, and there is not a single year between 2000 and 2021 for which every country has reported data. Moreover, there is no single way that countries report or calculate this data, so different countries will be arriving at their estimates in different ways. The dataset was posted by the United Nations and was last updated on October 25, 2023, with data last being pulled in April 2023. The data comes as a csv file and has 5,884 rows and 7 columns. It will be imported to R as a csv. [Link to data.](http://data.un.org/_Docs/SYB/PDFs/SYB66_154_202310_Health%20Personnel.pdf)

These datasets report the incidence rates and mortality rates of cancer by country in 2022. It is collected by the WHO and reported through the Global Cancer Observatory (GCO). The data are collected differently depending on the country. Some countries have national counts. Other countries have sub-national counts, and other countries do not have data so the WHO uses models to make estimates. This could pose some problems with analysis because the numbers for different countries are based on different methods of calculation. In some cases, the WHO extrapolates the data of a city or sub-region within the country to the overall country. In other cases, the WHO looks at rates in neighboring countries and applies those rates to the population of a country. Alternatively, they create models to estimate the prevalence and mortality rates. Because of the mix in raw data vs modeling data, it may not be comparing apples to apples in every country, but the WHO is the leading organization for this type of work and their numbers are probably the best that are possible to find. Both the incidence and mortality datasets have 13 columns and 186 rows. They are both csv files and will be imported into R as a csv. [Link to incidence data.](https://gco.iarc.who.int/today/en/dataviz/tables?mode=population&populations=100_104_108_112_116_12_120_124_132_140_144_148_152_160_170_174_178_180_188_191_192_196_203_204_208_214_218_222_226_231_232_233_24_242_246_250_254_258_262_266_268_270_275_276_288_300_31_312_316_32_320_324_328_332_340_348_352_356_36_360_364_368_372_376_380_384_388_392_398_4_40_400_404_408_410_414_417_418_422_426_428_430_434_44_440_442_450_454_458_462_466_470_474_478_48_480_484_496_498_499_50_504_508_51_512_516_52_524_528_540_548_554_558_56_562_566_578_586_591_598_600_604_608_616_620_624_626_630_634_638_64_642_643_646_662_678_68_682_686_688_694_70_702_703_704_705_706_710_716_72_724_728_729_740_748_752_756_76_760_762_764_768_780_784_788_792_795_8_800_804_807_818_826_834_84_840_854_858_860_862_882_887_894_90_96&multiple_populations=1) [Link to mortality data.](https://gco.iarc.who.int/today/en/dataviz/tables?mode=population&populations=100_104_108_112_116_12_120_124_132_140_144_148_152_160_170_174_178_180_188_191_192_196_203_204_208_214_218_222_226_231_232_233_24_242_246_250_254_258_262_266_268_270_275_276_288_300_31_312_316_32_320_324_328_332_340_348_352_356_36_360_364_368_372_376_380_384_388_392_398_4_40_400_404_408_410_414_417_418_422_426_428_430_434_44_440_442_450_454_458_462_466_470_474_478_48_480_484_496_498_499_50_504_508_51_512_516_52_524_528_540_548_554_558_56_562_566_578_586_591_598_600_604_608_616_620_624_626_630_634_638_64_642_643_646_662_678_68_682_686_688_694_70_702_703_704_705_706_710_716_72_724_728_729_740_748_752_756_76_760_762_764_768_780_784_788_792_795_8_800_804_807_818_826_834_84_840_854_858_860_862_882_887_894_90_96&multiple_populations=1&types=1)

## Missing value analysis

```{r}
#| message: FALSE
library(dplyr)
library(ggplot2)
library(RColorBrewer)

#write.csv(un_health_personnel, "un_health_personnel.csv")

un_health_personnel <- read.csv("un_health_personnel.csv")

un_health_personnel |> 
  filter(Series == "Health personnel: Physicians (number)") |> 
  group_by(Year) |> 
  summarize(count=n()) |>
  mutate(missing_percent = 100 - (((count)/n_distinct(un_health_personnel$Region.Country.Area))*100)) |> 
  ungroup() -> un_health_personnel_number_summary

ggplot(data = un_health_personnel_number_summary, aes(x=1, y=as.factor(Year)))+
  geom_tile(aes(fill=missing_percent))+
  labs(y="Year", fill = "% of Countries\n without Data", title = "Missing Physician Data by Year")+
  scale_fill_distiller(palette = "Reds", direction = 1, limits = c(0,100))+
  theme_minimal()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```
The data for number of physicians operating inside countries is inconsistently reported depending on the country. Every country has reported some data between 2000 and 2021, but very few years have a majority of countries reporting. It appears that 2010 and 2015 are the years that have the most countries reporting this data. 2005, 2020, and 2004 are also years where large numbers of countries have reported data. To make up for the inconsistency of the reporting, we will ultimately take averages across several year spans in order to get usable data for the most countries possible. In this range, some countries will have reported data for several of the years. Others may have only reported data for one year, but averaging across several years of data will allow us to draw comparisons across as many countries as possible over a similar time span.
