# Introduction


  Cancer is a broad term for a variety of diseases that arise from abnormal growth in the body. The World Health Organization (WHO) states that cancer is one of the leading causes of death in the world and that cancer deaths can be prevented if the disease is diagnosed early and treated appropriately. Some of the factors contributing to early diagnosis are the level of healthcare access a patient has and the healthcare policies in the country of residence. For example, women in countries with a lower human development index (HDI) are 50% less likely to be diagnosed with breast cancer than women in high HDI countries, but are more likely to die from breast cancer due to inequity in health care access and treatment.  Additionally, there may be other barriers in access to diagnosis and treatment such as race, sex and age. In this project, we intend to explore trends for cancer diagnosis and treatment based on patient and country characteristics.

  We chose this topic because we are interested in investigating the cancer rates and healthcare policies around the world and by U.S. state and potential trends that reveal more about cancer diagnosis and treatment. We want to explore who is most affected by cancer (i.e. genders, ages, races, and countries) and whether the governments’ policies on healthcare expenditures and/or health insurance systems play a role in positive or negative outcomes. We aim to explore how cancer rates differ by demographic group and by country (and state). We also plan to explore whether both cancer rates and cancer mortality rates appear associated with different amounts of healthcare spending, the number of physicians operating in a country, and potentially even rates of insurance coverage within the population.

Sources: [WHO Cancer Fact Sheet](https://www.who.int/news-room/fact-sheets/detail/cancer)
[WHO Article: Global Cancer Burden Growing](https://www.who.int/news/item/01-02-2024-global-cancer-burden-growing--amidst-mounting-need-for-services#:~:text=In%202022%2C%20there%20were%20an%20estimated%2020%20million,1%20in%2012%20women%20die%20from%20the%20disease)
